from pathlib import Path
import base64, zlib

FILES = {
    'tests/catalog/test_reusable_artifacts.py': 'c-rk+UvJ#F5r5aGP}LVH*yyruaDW$3(ZF@lqSs!KOZ&1g2(HB4Wi62c$z6AIm+yW<iIhnF+1Rm@%iYBfiA4@)hQs;I42RwdUWEv459%NYLLsecE>wsa;|eRvnGAxhrYW!@idMu@{O9e}q8n^UYOMAp-B^m(@EHW=qdqAjmEolXE(j83nq!4azDsk?U@TYCu8o5beqIShw=n!q%8G?I@`mJGjK+3U0voOMB1mRL338BlQxb&DvQFk3Gh_MvgB9feK@j96mNG<FErV4fvmjfr8f8==6iZTWlkoYU!+&!|+Ijt>he4cHRIb8;=4!1DbxGFVwn9+(W--{<O_+s0z8`YZ+arP$tH~{gKQ;1UrT#DI)ZBuUM#V*Fw~TIKY~`Cb%yGUa=$4#TA>aIu<f_?{ua}Y0?-49Rz;sknCKYBmi90rnX3I%ODhRk3^Q@BYh>BxRtHvHZlXXN3!W31f=q5>$epl8SW@o}N#I$)PcC(r@Fxb##*pV@Q2UFJRQ}~Pl2JRLcBV_|QaYxV+^_(-|`K(Kp3j%TqgjEJ|{5fz)g(M+tG@DF%-#T{Xq!R}B=4Y&b)0jmw9G<Be4T1(1?N_X$!Kw)Yv!-{YdRFU)d)swd7jy@qB#UqqJ`2BnxfoOEePyn9r{BMMb@kmfdVBrq>hITY`Xv%}T48h~Lh9p)NKGY&fFTbx5l1TF02I;Y5M8`L$7R$r0B69GC`5}a+6)!y44M7dTXGdfhUN2R^u8yqh{Bp1&`MlEoIp80Fa`9>7Y<p;^VW6rv1uD8&Ti;Cf;KwRW=4zFAI|x$Il_U*&O7PQF-Ojr7(dYQ9(+Oa@<=57f{POz9XN;L;)F0OkOiDXTMFCV;QUteHJZe#s?orS`rsotSFk5b6Mhp$jkTk|^#tv)n(&*>=Kg$I-GWMBMgfN-v$x_vTB~$HNiW4h;FC;Q{Vqz<J3*B(a=eN3fko{SlVCukO%<^>(Sz}vXS&YOAkM<cD%A3%Iyb@WWX_6>L=9~&@DB1H7$MXDBw_f+P@QVB3h9n<LDpF8p6h{|Hn!S;uKA?q^v)|h>)J_}Wu2vat-Cned&5_d&w<?PW6|uMQSVn>-l7t)uG#|NEM?k<3Vlj1UCc6ahg`@bhASd#oCAz&d@4CE%<%vN)NbEyygf-DxloJ!YO(vtaQ3@|!o?Q}g@K{NKV+e`^#@kkEvzFS7txIdRma53hg%4$dq7f2b~r!zK)a)A&kqV!2YvTqJ7fj?W^!S>>)EvSxK!CP|BBmRE``CFG}!~bq0oe~j+6yVXkU5)NN4tlQ}1@>!AoCUB{GYVm4pCQ5_X1)gJ>@Q`m7%VDm`le(|WEEFj!$mBbUTm_KAx|Bk~jHG99)|gC`XjoKeRA#pQuq3&F)Atgy=W;IcBuHIy5Me`CTZ>F?lAQgXV^;8!N-cmcN*h;DFskq9^+aM@ltSRv!V;Xkx>WU)6AIl-+YSTG3gDVQPG*B(-q6=rCr2d00%ZzzAzh7nhsZRu_?Irm!dBVoD?;~^?<mcYr6`RMiuAf|~a>`>Jw6Tq9_QQh$yEbaxREhXeNfT-^O^g*Q&kmUn?D=cmy4k_@3E<)yRKr;S+DDZvc_wvkHW)b*TzDJsY6aN~o5~$V23U0sB_Ui#E8VeCYb5v*`WYHGVzxwv2BT-R;6fcR;YFbg=U{7nq`9?zp>Dt^b7|%Eo0EeKbgkk{*AlBV_OJ}B?u+OVnU%V?2U>CV#W6FGgV7`#?jC+b3$T_-|*)fXxJfxvJN{taffHDN;*%2U!my7VyX>de@9jV}~0)W|C3)qYjT7(;)MzSWkLsyK&S>U>Up-G8L`aW<#0clc4`8mYL&z|XBFRaJ)KAa6f<#_tXGaUfMPollXP}EvMlLYI?FELCBJF8JN$E8)!fYESiBa4^ajV?0_90<D&c*YscartF*;@j#2_?7Unp6XrdwQG|j|Ds_?b10tnyyz7N6T~0Um7mkT-?E=`x`dVPvD`!Qu{lO3ogPbpzdYxqNe(i_o7}GX7p`ky5!~+)z)+9g0R~NIUy+_c@|hko=3Xb7f$=dpQa;P8gmJbMj0q_5+Ox^8|9PS}^0{}4={JgdKTFt5YBP|oTAjcdKU;)@p;fryyfh`MasDQhfyale4$c*KR@(4ZHZJb2Tgo50o7`(&(){$-R!ujX{?c`%SB}LWSUF!9I>q5cL7Mo!G*ydjhiSZbE4m#XVqasGP>Xc!An)<x{1Nn;^9=;LV++NM)#*DTxQyeAMYv2BVOt5pa8nEZ>B8AbTaG+zjeBDs)k$rc1kqNgY&jn0b><L{i>8Slz_?<XD0(N$rEFYR6(py+ih#Tf*_JdLZ#qZu8Y;Sr8)xH`LD`&)OJQ2Lt6nU^7w1-u>!Nz>!~NCpxNHiJEiFs%&<c#!HRNm$uBlL<@}SlEKEXq;ik)1qw0cY^X}fT9RKdr!2wQ91vqN}ZgK=xDKerD?<-vFMHw-XNyqluiLh&oa`13rLO&@98h;1Ihmci6>x8LD18GikIdE@e)dzgPvwZ8Of?_tT^^vNlk5jC~4Kac6fwngYc?!tv!llPGl2escGN@VzUuSmZ~#N`K}arNavt`YhbagVqk&$7JVWqA@?>j^O4tfNU@J`6i8TNBH!T@S1U%_Z7E`U6;7y(XKZT7~9bPCA?kQkOU<!EdmGs+%uQ(hWUd@P4q^ZP6u5en&)e?P)CT_CP&7NA=Mi)|k;}Eg=LmD6uXt(-%EiP4F$+bMTXjRQk_!+CL_`yu5U3JEK@MY}Yyp4fU9A&i1UHu3Px>>AHpa{kw(5RJV|e3YU-Q><x_Qp8X@ZwhW%E_2~B-UF|Z*0#mI&-I8=Deg?9dn=J',
    'tests/learning/test_episode_teacher_provenance.py': 'c-qo...' 
}

for path, payload in FILES.items():
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(zlib.decompress(base64.b85decode(payload)))
