from pathlib import Path


def replace_once(path: Path, old: str, new: str) -> None:
    content = path.read_text(encoding="utf-8")
    if old not in content:
        raise SystemExit(f"documentation anchor missing: {path}: {old[:60]!r}")
    path.write_text(content.replace(old, new, 1), encoding="utf-8")


binance = Path("docs/BINANCE.md")
replace_once(
    binance,
    "Binance Vision does not publish complete exchange metadata. A general Vision-only dataset may therefore provide `--tick-size`, `--lot-size`, `--minimum-notional`, and `--listed-at` once per symbol; those static values participate in the dataset identity. The maintained strict multi-timeframe research workflow is stronger: it requires an authenticated effective-dated rule history and materializes tick size, lot size, and minimum notional per bar. It refuses to treat current `exchangeInfo` as historical metadata.\n",
    """Binance Vision does not publish complete exchange metadata. A general Vision-only dataset may therefore provide `--tick-size`, `--lot-size`, `--minimum-notional`, and `--listed-at` once per symbol; those static values participate in the dataset identity. The maintained multi-timeframe runner never silently upgrades static values into historical facts. It resolves one explicit execution-metadata mode before either repeated dataset build and binds the canonical evidence payload into `dataset_id`.\n\n## Execution-metadata modes\n\nThe full runner accepts `--metadata-mode` and the equivalent `TRADE_RL_METADATA_MODE` environment variable. The modes are deliberately not interchangeable:\n\n- `historical_signed` is the highest-integrity mode. It verifies the existing HMAC envelope, requires complete effective-dated rule coverage for every selected symbol, and reports authenticated point-in-time evidence.\n- `frozen_snapshot` is the maintained Docker default. It fetches the official USDⓈ-M `exchangeInfo` response exactly once, preserves the received bytes, source URI, aware UTC retrieval time and raw SHA-256, then applies those current rules statically across the research interval. It is explicitly unauthenticated and non-point-in-time.\n- `conservative_static` requires an explicit versioned JSON payload supplied with `--conservative-static-path` or `TRADE_RL_CONSERVATIVE_STATIC_PATH`. It is a declared approximation and is never described as Binance historical evidence.\n\n`frozen_snapshot` writes `exchange-info.raw.json` byte-for-byte and every mode writes canonical `exchange-info.json`. Mode, source, evidence digest, as-of time, coverage, authentication state, point-in-time state, policy version and limitations are repeated in the dataset result and final summary. Dataset A and B reuse the same in-memory resolution, so a live metadata change cannot occur between the reproducibility builds.\n\n## Conservative closed-loop execution sensitivity\n\nWhen the walk-forward configuration declares execution sensitivity, replay occurs only after model and seed-ensemble selection. The selected policy and the shadow baseline are rerun on the same sealed OOS folds with unchanged normalizers under nominal, each-rule 2x, joint 2x and joint 5x conditions. This is a closed-loop replay: changed tick, lot and minimum-notional constraints affect fills, positions and later observations; returns are not adjusted after evaluation.\n\nThe immutable `execution-sensitivity.json` artifact is bound to the dataset identity, experiment-plan digest, scenario-pack digest and base sealed-test access evidence. Joint 2x must retain positive selected return, nonnegative uplift over baseline and maximum independently reset fold drawdown no greater than 20%. Joint 5x is report-only until calibrated. Sensitivity never participates in recipe selection, and all results remain research-only with production status `NO-GO`.\n""",
)

runbook = Path("docs/operations/docker-gpu-full-training.md")
replace_once(
    runbook,
    """Before starting strict research, place an authenticated point-in-time Binance execution-rule history inside the named volume (for example `/workspace/var/metadata/binance-rule-history.json`) and configure the in-container path plus trusted key map:\n\n```powershell\n$env:TRADE_RL_BINANCE_RULE_HISTORY = \"/workspace/var/metadata/binance-rule-history.json\"\n$env:TRADE_RL_METADATA_KEYS = '{\"binance-metadata-2026\":\"replace-with-secret-from-your-secret-store\"}'\n```\n\nThe `binance_instrument_rule_history_v2` payload must contain the authoritative listing time and an ordered execution-rule history for every selected symbol. Its first rule must be effective no later than the requested dataset start, and the history must cover the full research interval. The runner verifies its HMAC-SHA256 envelope and fails closed when the file, trusted key, signature, symbol history, or coverage is missing. Strict research does not use current `exchangeInfo` as historical evidence. Do not commit signing keys.\n""",
    """Choose the execution-metadata evidence mode before starting. The Docker workflow defaults to the transparent current snapshot mode:\n\n```powershell\n$env:TRADE_RL_METADATA_MODE = \"frozen_snapshot\"\n```\n\n`frozen_snapshot` requests the official USDⓈ-M `exchangeInfo` payload once, stores the exact response bytes and SHA-256, and applies the captured rules statically across the research interval. Reports mark it unauthenticated and non-point-in-time; it is not represented as official historical evidence. No Binance account or API key is used.\n\nFor the highest-integrity mode, place an authenticated point-in-time rule history inside the named volume and explicitly opt in:\n\n```powershell\n$env:TRADE_RL_METADATA_MODE = \"historical_signed\"\n$env:TRADE_RL_BINANCE_RULE_HISTORY = \"/workspace/var/metadata/binance-rule-history.json\"\n$env:TRADE_RL_METADATA_KEYS = '{\"binance-metadata-2026\":\"replace-with-secret-from-your-secret-store\"}'\n```\n\nThe `binance_instrument_rule_history_v2` payload must contain authoritative listing time and ordered execution-rule history for every selected symbol. The runner verifies its HMAC-SHA256 envelope and complete requested-period coverage. Missing files, unknown keys, altered signatures, missing symbols or coverage gaps fail before dataset publication. Do not commit signing keys.\n\n`conservative_static` is available only with an explicit versioned payload and must also be selected explicitly:\n\n```powershell\n$env:TRADE_RL_METADATA_MODE = \"conservative_static\"\n$env:TRADE_RL_CONSERVATIVE_STATIC_PATH = \"/workspace/var/metadata/binance-conservative-static.json\"\n```\n\nThis mode remains a declared approximation. It never sets authenticated or point-in-time status and never relabels internally maintained static values as Binance history.\n""",
)
replace_once(
    runbook,
    """- `/workspace/var/runs/full-20260715-120000/training.log`\n- `/workspace/var/runs/full-20260715-120000/walk-forward.log`\n- `/workspace/var/runs/full-20260715-120000/research-gate.json`\n- `/workspace/var/runs/full-20260715-120000/summary.json`\n- `/workspace/var/runs/full-20260715-120000/artifacts/`\n""",
    """- `/workspace/var/runs/full-20260715-120000/exchange-info.json`\n- `/workspace/var/runs/full-20260715-120000/exchange-info.raw.json` in `frozen_snapshot` mode\n- `/workspace/var/runs/full-20260715-120000/training.log`\n- `/workspace/var/runs/full-20260715-120000/walk-forward.log`\n- `/workspace/var/runs/full-20260715-120000/execution-sensitivity.json`\n- `/workspace/var/runs/full-20260715-120000/research-gate.json`\n- `/workspace/var/runs/full-20260715-120000/summary.json`\n- `/workspace/var/runs/full-20260715-120000/artifacts/`\n""",
)
replace_once(
    runbook,
    """The maintained gate requires six sealed walk-forward folds covering at least 180 OOS days. It rejects a candidate when the paired circular block-bootstrap lower confidence bound on daily log-return excess over the shadow baseline is non-positive, material mean uplift is below the configured threshold, or drawdown, turnover, cost fraction, seed stability or selection stability violates configured limits. Every fold evaluates the exact deterministic mean action across the fixed seed members used by serving. A separate signed fresh-confirmation interval is opened only after the recipe and ensemble are frozen; confirmation metrics are recomputed from the authenticated return series and identity-bound reconciliation evidence.\n""",
    """The maintained gate requires six sealed walk-forward folds covering at least 180 OOS days. It rejects a candidate when the paired circular block-bootstrap lower confidence bound on daily log-return excess over the shadow baseline is non-positive, material mean uplift is below the configured threshold, or drawdown, turnover, cost fraction, seed stability or selection stability violates configured limits. Every fold evaluates the exact deterministic mean action across the fixed seed members used by serving.\n\nAfter selection, the same frozen policy and baseline are replayed under the identity-bound execution-sensitivity pack. Joint 2x is required to retain positive selected return, nonnegative baseline uplift and maximum independently reset fold drawdown at or below 20%; joint 5x is report-only. Scenario replay is closed-loop and cannot influence candidate or checkpoint selection. The resulting `execution-sensitivity.json` digest is verified again by the full runner before its result is combined with the research gate. A separate signed fresh-confirmation interval is opened only after the recipe and ensemble are frozen; confirmation metrics are recomputed from the authenticated return series and identity-bound reconciliation evidence.\n""",
)

readme = Path("README.md")
replace_once(
    readme,
    """Nested walk-forward execution builds fold-local causal signals, fits only exogenous normalization statistics on each train capability, records one-shot sealed-test access, and evaluates the exact deterministic mean seed ensemble used by serving on the outer test range only after selection. Training, behavior cloning, checkpoint selection and sealed evaluation all use liquidation-at-close terminal accounting. Independent folds retain full execution evidence and are reported as a distribution; continuous return and drawdown are produced only with verified contiguous account-state handoff.\n""",
    """Nested walk-forward execution builds fold-local causal signals, fits only exogenous normalization statistics on each train capability, records one-shot sealed-test access, and evaluates the exact deterministic mean seed ensemble used by serving on the outer test range only after selection. Training, behavior cloning, checkpoint selection and sealed evaluation all use liquidation-at-close terminal accounting. Independent folds retain full execution evidence and are reported as a distribution; continuous return and drawdown are produced only with verified contiguous account-state handoff. An optional identity-bound post-selection execution-sensitivity pack replays the selected ensemble and baseline closed-loop under nominal, individual 2x, joint 2x and report-only joint 5x rule stresses without participating in selection.\n""",
)
replace_once(
    readme,
    """The strict Binance workflow also requires an authenticated point-in-time execution-rule history. Set `TRADE_RL_BINANCE_RULE_HISTORY` to the in-container JSON path and `TRADE_RL_METADATA_KEYS` to a JSON map of trusted key IDs to secrets. Current `exchangeInfo` values are never silently projected backward across the research period.\n""",
    """The Docker workflow defaults to `TRADE_RL_METADATA_MODE=frozen_snapshot`: one official current `exchangeInfo` payload is preserved byte-for-byte, identity-bound and disclosed as unauthenticated, non-point-in-time evidence. `historical_signed` remains the highest-integrity explicit opt-in and requires `TRADE_RL_BINANCE_RULE_HISTORY` plus `TRADE_RL_METADATA_KEYS`; `conservative_static` requires a versioned payload path. No mode silently projects current values backward as historical truth. The full preset also publishes identity-bound closed-loop execution sensitivity and requires the joint-2x research gate while keeping joint 5x report-only.\n""",
)
