from __future__ import annotations

from pathlib import Path

path = Path("trade_rl/learning/causal_alpha_teacher.py")
text = path.read_text(encoding="utf-8")
old = '''    finite_rows = np.isfinite(values).all(axis=1) & np.isfinite(target)\n    eligible_mask = (\n        finite_rows\n        & available.all(axis=1)\n        & (label_end >= 0)\n        & (label_end < knowledge_cutoff)\n    )\n    eligible_indices = np.flatnonzero(eligible_mask).astype(np.int64)\n    if eligible_indices.size < 2:\n        raise ValueError("causal alpha prefix contains insufficient fitted samples")\n    x = values[eligible_indices]\n    y = target[eligible_indices]\n    location = x.mean(axis=0, dtype=np.float64)\n    raw_scale = x.std(axis=0, dtype=np.float64)\n    constant_mask = raw_scale <= _EPSILON\n    scale = np.where(constant_mask, 1.0, raw_scale)\n    scaled = (x - location) / scale\n    scaled[:, constant_mask] = 0.0\n'''
new = '''    finite_rows = np.isfinite(values).all(axis=1) & np.isfinite(target)\n    eligible_mask = (\n        finite_rows\n        & (label_end >= 0)\n        & (label_end < knowledge_cutoff)\n    )\n    eligible_indices = np.flatnonzero(eligible_mask).astype(np.int64)\n    if eligible_indices.size < 2:\n        raise ValueError("causal alpha prefix contains insufficient fitted samples")\n    x = values[eligible_indices]\n    x_available = available[eligible_indices]\n    y = target[eligible_indices]\n\n    # Mirror the Universal observation contract: unavailable feature values are\n    # represented by standardized zero rather than discarding the entire row.\n    # Statistics are feature-local and use only values known to be available.\n    available_count = x_available.sum(axis=0, dtype=np.int64)\n    available_sum = np.where(x_available, x, 0.0).sum(axis=0, dtype=np.float64)\n    location = np.zeros(x.shape[1], dtype=np.float64)\n    np.divide(\n        available_sum,\n        available_count,\n        out=location,\n        where=available_count > 0,\n    )\n    centered = np.where(x_available, x - location, 0.0)\n    squared_sum = np.square(centered).sum(axis=0, dtype=np.float64)\n    variance = np.zeros(x.shape[1], dtype=np.float64)\n    np.divide(\n        squared_sum,\n        available_count,\n        out=variance,\n        where=available_count > 0,\n    )\n    raw_scale = np.sqrt(variance)\n    constant_mask = (available_count < 2) | (raw_scale <= _EPSILON)\n    scale = np.where(constant_mask, 1.0, raw_scale)\n    scaled = np.where(x_available, (x - location) / scale, 0.0)\n    scaled[:, constant_mask] = 0.0\n'''
if text.count(old) != 1:
    raise SystemExit("causal ridge availability patch target drifted")
path.write_text(text.replace(old, new), encoding="utf-8")
